ARG BASE_IMAGE=registry.cn-hangzhou.aliyuncs.com/rcf/humble:latest 
FROM $BASE_IMAGE

USER root

RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
RUN bash Miniforge3-Linux-x86_64.sh -p /opt/miniforge3 -b

RUN rm Miniforge3-Linux-x86_64.sh

USER robot

WORKDIR /home/robot
ENV PATH="/opt/miniforge3/bin:$PATH"